deployments:
- name: taxi_local_data
  entrypoint: 03-orchestration/3.4/orchestrate.py:main_flow
  work_pool:
    name: zoompool
- name: taxi_s3_data
  entrypoint: 03-orchestration/3.5/orchestrate_s3.py:main_flow_s3
  work_pool:
    name: zoompool
- name: q3
  entrypoint: cohorts/2023/03-orchestration/q3_orchestrate.py:main_flow_hw_m3_q3
  work_pool:
    name: zoompool
- name: q4
  entrypoint: cohorts/2023/03-orchestration/q4_orchestrate.py:main_flow_hw_m3_q4
  work_pool:
    name: zoompool
- name: q5
  entrypoint: cohorts/2023/03-orchestration/q5_send_email.py:send_email_hw_m3_q5
  work_pool:
    name: zoompool